spring.application.name=SBMS

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Enable custom info properties
management.info.env.enabled=true

# Optional: show health details
management.endpoint.health.show-details=always
